<?php

namespace Database\Seeders;

use App\Models\Peserta;
use Illuminate\Database\Seeder;

class PesertaSeeder extends Seeder
{
    public function run(): void
    {
        $peserta = [
            [
                'nama' => 'Fadhilla Firma',
                'nim' => '2311522031',
                'email' => 'fadhilla@mail.com',
                'telepon' => '081234567890',
                'pilihan_divisi_1' => 'Konsumsi',
                'pilihan_divisi_2' => 'Acara',
                'alasan_1' => 'Suka masak',
                'alasan_2' => 'Suka keramaian',
                'tanggal_jadwal' => '15 Okt 2025',
                'waktu_jadwal' => '07.00 WIB',
                'lokasi' => 'Sekretariat BEM KM FTI',
            ],
            [
                'nama' => 'Afiq Congkel',
                'nim' => '2311523011',
                'email' => 'afiq@mail.com',
                'telepon' => '081234567891',
                'pilihan_divisi_1' => 'Humas',
                'pilihan_divisi_2' => 'Pubdok',
                'alasan_1' => 'Suka komunikasi',
                'alasan_2' => 'Suka foto',
                'tanggal_jadwal' => '15 Okt 2025',
                'waktu_jadwal' => '08.00 WIB',
                'lokasi' => 'Sekretariat BEM KM FTI',
            ],
            [
                'nama' => 'Farhan Firki',
                'nim' => '2311522037',
                'email' => 'farhan@mail.com',
                'telepon' => '081234567892',
                'pilihan_divisi_1' => 'Perlengkapan',
                'pilihan_divisi_2' => 'Keamanan',
                'alasan_1' => 'Suka angkat-angkat',
                'alasan_2' => 'Suka ketertiban',
                'tanggal_jadwal' => '15 Okt 2025',
                'waktu_jadwal' => '09.00 WIB',
                'lokasi' => 'Sekretariat BEM KM FTI',
            ],
            [
                'nama' => 'Diaz Jelek Hitam',
                'nim' => '2311521015',
                'email' => 'diaz@mail.com',
                'telepon' => '081234567893',
                'pilihan_divisi_1' => 'Acara',
                'pilihan_divisi_2' => 'Konsumsi',
                'alasan_1' => 'Suka buat event',
                'alasan_2' => 'Suka ngemil',
                'tanggal_jadwal' => '15 Okt 2025',
                'waktu_jadwal' => '10.00 WIB',
                'lokasi' => 'Sekretariat BEM KM FTI',
            ],
            [
                'nama' => 'Nadya Putri',
                'nim' => '2311522045',
                'email' => 'nadya@mail.com',
                'telepon' => '081234567894',
                'pilihan_divisi_1' => 'Humas',
                'pilihan_divisi_2' => 'Acara',
                'alasan_1' => 'Suka public speaking',
                'alasan_2' => 'Suka koordinasi',
                'tanggal_jadwal' => '17 Okt 2025',
                'waktu_jadwal' => '07.00 WIB',
                'lokasi' => 'Sekretariat BEM KM FTI',
            ],
            [
                'nama' => 'Dimas Aditya',
                'nim' => '2311522050',
                'email' => 'dimas@mail.com',
                'telepon' => '081234567895',
                'pilihan_divisi_1' => 'Pubdok',
                'pilihan_divisi_2' => 'Humas',
                'alasan_1' => 'Suka desain',
                'alasan_2' => 'Suka menulis',
                'tanggal_jadwal' => '17 Okt 2025',
                'waktu_jadwal' => '08.00 WIB',
                'lokasi' => 'Sekretariat BEM KM FTI',
            ],
            // ==========================================
            // Data tambahan untuk testing jadwal wawancara
            // ==========================================
            [
                'nama' => 'Siti Nurhaliza',
                'nim' => '2311522040',
                'email' => 'siti.nurhaliza@student.unand.ac.id',
                'telepon' => '081234567894',
                'jurusan' => 'Teknik Informatika',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Humas',
                'pilihan_divisi_2' => 'Pubdok',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya memiliki kemampuan public speaking dan suka berkomunikasi.',
                'alasan_2' => 'Saya juga tertarik dengan dokumentasi dan desain.',
                'alasan_3' => null,
                'tanggal_jadwal' => '15 Okt 2025',
                'waktu_jadwal' => '11.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Budi Santoso',
                'nim' => '2311522055',
                'email' => 'budi.santoso@student.unand.ac.id',
                'telepon' => '081234567895',
                'jurusan' => 'Sistem Informasi',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Perlengkapan',
                'pilihan_divisi_2' => 'Keamanan',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya suka mengatur dan mengorganisir perlengkapan.',
                'alasan_2' => 'Saya juga bisa membantu menjaga keamanan acara.',
                'alasan_3' => null,
                'tanggal_jadwal' => '15 Okt 2025',
                'waktu_jadwal' => '13.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Indah Permata',
                'nim' => '2311522060',
                'email' => 'indah.permata@student.unand.ac.id',
                'telepon' => '081234567896',
                'jurusan' => 'Teknik Informatika',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Konsumsi',
                'pilihan_divisi_2' => 'Acara',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya suka memasak dan memiliki resep-resep makanan yang enak.',
                'alasan_2' => 'Saya juga tertarik membantu di bagian acara.',
                'alasan_3' => null,
                'tanggal_jadwal' => '15 Okt 2025',
                'waktu_jadwal' => '14.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Ahmad Rizki',
                'nim' => '2311523010',
                'email' => 'ahmad.rizki@student.unand.ac.id',
                'telepon' => '081234567897',
                'jurusan' => 'Teknik Komputer',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Pubdok',
                'pilihan_divisi_2' => 'Humas',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya memiliki skill desain grafis dan suka membuat konten.',
                'alasan_2' => 'Saya juga bisa membantu di bagian humas.',
                'alasan_3' => null,
                'tanggal_jadwal' => '16 Okt 2025',
                'waktu_jadwal' => '08.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Rina Sari',
                'nim' => '2311523020',
                'email' => 'rina.sari@student.unand.ac.id',
                'telepon' => '081234567898',
                'jurusan' => 'Sistem Informasi',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Acara',
                'pilihan_divisi_2' => 'Humas',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya memiliki pengalaman mengorganisir acara kampus.',
                'alasan_2' => 'Saya juga suka berkomunikasi dengan banyak orang.',
                'alasan_3' => null,
                'tanggal_jadwal' => '16 Okt 2025',
                'waktu_jadwal' => '09.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Putri Ayu',
                'nim' => '2311523060',
                'email' => 'putri.ayu@student.unand.ac.id',
                'telepon' => '081234567903',
                'jurusan' => 'Teknik Informatika',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Acara',
                'pilihan_divisi_2' => 'Konsumsi',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya memiliki pengalaman mengorganisir acara.',
                'alasan_2' => 'Saya juga suka membantu di bagian konsumsi.',
                'alasan_3' => null,
                'tanggal_jadwal' => '17 Okt 2025',
                'waktu_jadwal' => '09.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Andi Pratama',
                'nim' => '2311523070',
                'email' => 'andi.pratama@student.unand.ac.id',
                'telepon' => '081234567904',
                'jurusan' => 'Sistem Informasi',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Keamanan',
                'pilihan_divisi_2' => 'Perlengkapan',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya suka menjaga ketertiban dan keamanan acara.',
                'alasan_2' => 'Saya juga bisa membantu mengatur perlengkapan.',
                'alasan_3' => null,
                'tanggal_jadwal' => '17 Okt 2025',
                'waktu_jadwal' => '10.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
        ];

        foreach ($peserta as $p) {
            Peserta::create($p);
        }
    }
}
