<?php

namespace Database\Seeders;

use App\Models\JadwalRekrutmen;
use App\Models\Peserta;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

/**
 * Seeder untuk membuat data peserta dummy dengan jadwal wawancara
 * 
 * Seeder ini dibuat khusus untuk testing fitur Seleksi Wawancara
 * karena sistem development jadwal wawancara belum siap.
 * 
 * Data yang dibuat:
 * - 20+ peserta dengan jadwal wawancara
 * - Tersebar di beberapa hari (Senin, Selasa, Rabu, Kamis, Jumat)
 * - Berbagai waktu wawancara
 * - Lokasi yang bervariasi
 */
class PesertaJadwalWawancaraSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Data peserta dengan jadwal wawancara untuk testing
        $peserta = [
            // ==========================================
            // HARI SENIN - 15 Oktober 2025
            // ==========================================
            [
                'nama' => 'Fadhilla Firma',
                'nim' => '2311522031',
                'email' => 'fadhilla.firma@student.unand.ac.id',
                'telepon' => '081234567890',
                'jurusan' => 'Teknik Informatika',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Konsumsi',
                'pilihan_divisi_2' => 'Acara',
                'pilihan_divisi_3' => 'Humas',
                'alasan_1' => 'Saya suka memasak dan memiliki pengalaman dalam mengatur konsumsi untuk acara.',
                'alasan_2' => 'Saya juga tertarik dengan bagian acara karena suka koordinasi kegiatan.',
                'alasan_3' => 'Saya juga bisa membantu di bagian humas jika diperlukan.',
                'tanggal_jadwal' => '15 Okt 2025',
                'waktu_jadwal' => '07.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Afiq Congkel',
                'nim' => '2311523011',
                'email' => 'afiq.congkel@student.unand.ac.id',
                'telepon' => '081234567891',
                'jurusan' => 'Sistem Informasi',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Humas',
                'pilihan_divisi_2' => 'Pubdok',
                'pilihan_divisi_3' => 'Acara',
                'alasan_1' => 'Saya memiliki kemampuan komunikasi yang baik dan suka berinteraksi dengan banyak orang.',
                'alasan_2' => 'Saya juga tertarik dengan dokumentasi dan publikasi.',
                'alasan_3' => null,
                'tanggal_jadwal' => '15 Okt 2025',
                'waktu_jadwal' => '08.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Farhan Firki',
                'nim' => '2311522037',
                'email' => 'farhan.firki@student.unand.ac.id',
                'telepon' => '081234567892',
                'jurusan' => 'Teknik Informatika',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Perlengkapan',
                'pilihan_divisi_2' => 'Keamanan',
                'pilihan_divisi_3' => 'Konsumsi',
                'alasan_1' => 'Saya memiliki fisik yang kuat dan suka mengatur perlengkapan acara.',
                'alasan_2' => 'Saya juga bisa membantu di bagian keamanan untuk menjaga ketertiban.',
                'alasan_3' => null,
                'tanggal_jadwal' => '15 Okt 2025',
                'waktu_jadwal' => '09.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Diaz Jelek Hitam',
                'nim' => '2311521015',
                'email' => 'diaz.jelek@student.unand.ac.id',
                'telepon' => '081234567893',
                'jurusan' => 'Teknik Komputer',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Acara',
                'pilihan_divisi_2' => 'Konsumsi',
                'pilihan_divisi_3' => 'Pubdok',
                'alasan_1' => 'Saya memiliki pengalaman membuat event dan suka mengkoordinasi kegiatan.',
                'alasan_2' => 'Saya juga suka membantu di bagian konsumsi.',
                'alasan_3' => null,
                'tanggal_jadwal' => '15 Okt 2025',
                'waktu_jadwal' => '10.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Siti Nurhaliza',
                'nim' => '2311522040',
                'email' => 'siti.nurhaliza@student.unand.ac.id',
                'telepon' => '081234567894',
                'jurusan' => 'Teknik Informatika',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Humas',
                'pilihan_divisi_2' => 'Pubdok',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya memiliki kemampuan public speaking dan suka berkomunikasi.',
                'alasan_2' => 'Saya juga tertarik dengan dokumentasi dan desain.',
                'alasan_3' => null,
                'tanggal_jadwal' => '15 Okt 2025',
                'waktu_jadwal' => '11.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Budi Santoso',
                'nim' => '2311522050',
                'email' => 'budi.santoso@student.unand.ac.id',
                'telepon' => '081234567895',
                'jurusan' => 'Sistem Informasi',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Perlengkapan',
                'pilihan_divisi_2' => 'Keamanan',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya suka mengatur dan mengorganisir perlengkapan.',
                'alasan_2' => 'Saya juga bisa membantu menjaga keamanan acara.',
                'alasan_3' => null,
                'tanggal_jadwal' => '15 Okt 2025',
                'waktu_jadwal' => '13.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Indah Permata',
                'nim' => '2311522060',
                'email' => 'indah.permata@student.unand.ac.id',
                'telepon' => '081234567896',
                'jurusan' => 'Teknik Informatika',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Konsumsi',
                'pilihan_divisi_2' => 'Acara',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya suka memasak dan memiliki resep-resep makanan yang enak.',
                'alasan_2' => 'Saya juga tertarik membantu di bagian acara.',
                'alasan_3' => null,
                'tanggal_jadwal' => '15 Okt 2025',
                'waktu_jadwal' => '14.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],

            // ==========================================
            // HARI SELASA - 16 Oktober 2025
            // ==========================================
            [
                'nama' => 'Ahmad Rizki',
                'nim' => '2311523010',
                'email' => 'ahmad.rizki@student.unand.ac.id',
                'telepon' => '081234567897',
                'jurusan' => 'Teknik Komputer',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Pubdok',
                'pilihan_divisi_2' => 'Humas',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya memiliki skill desain grafis dan suka membuat konten.',
                'alasan_2' => 'Saya juga bisa membantu di bagian humas.',
                'alasan_3' => null,
                'tanggal_jadwal' => '16 Okt 2025',
                'waktu_jadwal' => '08.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Rina Sari',
                'nim' => '2311523020',
                'email' => 'rina.sari@student.unand.ac.id',
                'telepon' => '081234567898',
                'jurusan' => 'Sistem Informasi',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Acara',
                'pilihan_divisi_2' => 'Humas',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya memiliki pengalaman mengorganisir acara kampus.',
                'alasan_2' => 'Saya juga suka berkomunikasi dengan banyak orang.',
                'alasan_3' => null,
                'tanggal_jadwal' => '16 Okt 2025',
                'waktu_jadwal' => '09.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Dedi Kurniawan',
                'nim' => '2311523030',
                'email' => 'dedi.kurniawan@student.unand.ac.id',
                'telepon' => '081234567899',
                'jurusan' => 'Teknik Informatika',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Perlengkapan',
                'pilihan_divisi_2' => 'Keamanan',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya suka mengatur dan merapikan perlengkapan acara.',
                'alasan_2' => 'Saya juga bisa membantu menjaga keamanan.',
                'alasan_3' => null,
                'tanggal_jadwal' => '16 Okt 2025',
                'waktu_jadwal' => '10.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Lina Marlina',
                'nim' => '2311523040',
                'email' => 'lina.marlina@student.unand.ac.id',
                'telepon' => '081234567900',
                'jurusan' => 'Teknik Informatika',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Konsumsi',
                'pilihan_divisi_2' => 'Acara',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya suka memasak dan membuat menu makanan untuk acara.',
                'alasan_2' => 'Saya juga tertarik dengan koordinasi acara.',
                'alasan_3' => null,
                'tanggal_jadwal' => '16 Okt 2025',
                'waktu_jadwal' => '13.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],

            // ==========================================
            // HARI RABU - 17 Oktober 2025
            // ==========================================
            [
                'nama' => 'Nadya Putri',
                'nim' => '2311522045',
                'email' => 'nadya.putri@student.unand.ac.id',
                'telepon' => '081234567901',
                'jurusan' => 'Sistem Informasi',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Humas',
                'pilihan_divisi_2' => 'Acara',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya memiliki kemampuan public speaking yang baik.',
                'alasan_2' => 'Saya juga suka mengkoordinasi kegiatan.',
                'alasan_3' => null,
                'tanggal_jadwal' => '17 Okt 2025',
                'waktu_jadwal' => '07.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Dimas Aditya',
                'nim' => '2311522050',
                'email' => 'dimas.aditya@student.unand.ac.id',
                'telepon' => '081234567902',
                'jurusan' => 'Teknik Komputer',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Pubdok',
                'pilihan_divisi_2' => 'Humas',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya memiliki skill desain dan dokumentasi yang baik.',
                'alasan_2' => 'Saya juga bisa membantu di bagian humas.',
                'alasan_3' => null,
                'tanggal_jadwal' => '17 Okt 2025',
                'waktu_jadwal' => '08.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Putri Ayu',
                'nim' => '2311523060',
                'email' => 'putri.ayu@student.unand.ac.id',
                'telepon' => '081234567903',
                'jurusan' => 'Teknik Informatika',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Acara',
                'pilihan_divisi_2' => 'Konsumsi',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya memiliki pengalaman mengorganisir acara.',
                'alasan_2' => 'Saya juga suka membantu di bagian konsumsi.',
                'alasan_3' => null,
                'tanggal_jadwal' => '17 Okt 2025',
                'waktu_jadwal' => '09.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Andi Pratama',
                'nim' => '2311523070',
                'email' => 'andi.pratama@student.unand.ac.id',
                'telepon' => '081234567904',
                'jurusan' => 'Sistem Informasi',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Keamanan',
                'pilihan_divisi_2' => 'Perlengkapan',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya suka menjaga ketertiban dan keamanan acara.',
                'alasan_2' => 'Saya juga bisa membantu mengatur perlengkapan.',
                'alasan_3' => null,
                'tanggal_jadwal' => '17 Okt 2025',
                'waktu_jadwal' => '10.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Sinta Dewi',
                'nim' => '2311523080',
                'email' => 'sinta.dewi@student.unand.ac.id',
                'telepon' => '081234567905',
                'jurusan' => 'Teknik Informatika',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Pubdok',
                'pilihan_divisi_2' => 'Humas',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya memiliki skill desain grafis dan content creation.',
                'alasan_2' => 'Saya juga suka berkomunikasi dengan banyak orang.',
                'alasan_3' => null,
                'tanggal_jadwal' => '17 Okt 2025',
                'waktu_jadwal' => '13.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Rizki Ramadhan',
                'nim' => '2311523090',
                'email' => 'rizki.ramadhan@student.unand.ac.id',
                'telepon' => '081234567906',
                'jurusan' => 'Teknik Komputer',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Konsumsi',
                'pilihan_divisi_2' => 'Acara',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya suka memasak dan memiliki pengalaman dalam katering.',
                'alasan_2' => 'Saya juga tertarik dengan koordinasi acara.',
                'alasan_3' => null,
                'tanggal_jadwal' => '17 Okt 2025',
                'waktu_jadwal' => '14.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],

            // ==========================================
            // HARI KAMIS - 18 Oktober 2025
            // ==========================================
            [
                'nama' => 'Maya Sari',
                'nim' => '2311523100',
                'email' => 'maya.sari@student.unand.ac.id',
                'telepon' => '081234567907',
                'jurusan' => 'Sistem Informasi',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Humas',
                'pilihan_divisi_2' => 'Pubdok',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya memiliki kemampuan komunikasi yang baik.',
                'alasan_2' => 'Saya juga tertarik dengan dokumentasi dan publikasi.',
                'alasan_3' => null,
                'tanggal_jadwal' => '18 Okt 2025',
                'waktu_jadwal' => '08.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Arief Maulana',
                'nim' => '2311523110',
                'email' => 'arief.maulana@student.unand.ac.id',
                'telepon' => '081234567908',
                'jurusan' => 'Teknik Informatika',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Perlengkapan',
                'pilihan_divisi_2' => 'Keamanan',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya suka mengatur dan merapikan perlengkapan.',
                'alasan_2' => 'Saya juga bisa membantu menjaga keamanan acara.',
                'alasan_3' => null,
                'tanggal_jadwal' => '18 Okt 2025',
                'waktu_jadwal' => '09.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Dewi Lestari',
                'nim' => '2311523120',
                'email' => 'dewi.lestari@student.unand.ac.id',
                'telepon' => '081234567909',
                'jurusan' => 'Teknik Komputer',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Acara',
                'pilihan_divisi_2' => 'Konsumsi',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya memiliki pengalaman mengorganisir acara kampus.',
                'alasan_2' => 'Saya juga suka membantu di bagian konsumsi.',
                'alasan_3' => null,
                'tanggal_jadwal' => '18 Okt 2025',
                'waktu_jadwal' => '10.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],

            // ==========================================
            // HARI JUMAT - 19 Oktober 2025
            // ==========================================
            [
                'nama' => 'Fajar Hidayat',
                'nim' => '2311523130',
                'email' => 'fajar.hidayat@student.unand.ac.id',
                'telepon' => '081234567910',
                'jurusan' => 'Sistem Informasi',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Pubdok',
                'pilihan_divisi_2' => 'Humas',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya memiliki skill desain grafis dan video editing.',
                'alasan_2' => 'Saya juga bisa membantu di bagian humas.',
                'alasan_3' => null,
                'tanggal_jadwal' => '19 Okt 2025',
                'waktu_jadwal' => '08.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
            [
                'nama' => 'Nina Kartika',
                'nim' => '2311523140',
                'email' => 'nina.kartika@student.unand.ac.id',
                'telepon' => '081234567911',
                'jurusan' => 'Teknik Informatika',
                'angkatan' => '2023',
                'pilihan_divisi_1' => 'Konsumsi',
                'pilihan_divisi_2' => 'Acara',
                'pilihan_divisi_3' => null,
                'alasan_1' => 'Saya suka memasak dan memiliki resep makanan yang enak.',
                'alasan_2' => 'Saya juga tertarik dengan koordinasi acara.',
                'alasan_3' => null,
                'tanggal_jadwal' => '19 Okt 2025',
                'waktu_jadwal' => '09.00',
                'lokasi' => 'Sekretariat BEM KM FTI',
                'formulir_pendaftaran' => true,
                'surat_komitmen' => true,
                'pindah_divisi' => false,
            ],
        ];

        // Insert data peserta
        $jadwalByTanggal = [];
        foreach ($peserta as $p) {
            $tanggalJadwal = $p['tanggal_jadwal'] ?? null;
            $waktuJadwal = $p['waktu_jadwal'] ?? null;
            $lokasi = $p['lokasi'] ?? null;

            if (!empty($tanggalJadwal)) {
                if (!array_key_exists($tanggalJadwal, $jadwalByTanggal)) {
                    $jadwalByTanggal[$tanggalJadwal] = JadwalRekrutmen::create([
                        'judul' => 'Jadwal Wawancara ' . $tanggalJadwal,
                        'tanggal_mulai' => $tanggalJadwal,
                        'tanggal_selesai' => $tanggalJadwal,
                        'waktu_mulai' => $waktuJadwal ?? '09.00',
                        'waktu_selesai' => '15.00',
                        'pewawancara' => '-',
                        'lokasi' => $lokasi,
                    ]);
                }

                $p['jadwal_rekrutmen_id'] = $jadwalByTanggal[$tanggalJadwal]->id;
            }

            unset($p['tanggal_jadwal'], $p['waktu_jadwal'], $p['lokasi']);
            Peserta::create($p);
        }

        $this->command->info('✅ Data peserta dengan jadwal wawancara berhasil dibuat!');
        $this->command->info('📊 Total: ' . count($peserta) . ' peserta');
    }
}

